#ifndef Wifi_portal_WEB_H
#define Wifi_portal_WEB_H

const char* wifi_portal_html_src = "<!DOCTYPE html>\n\n<head lang=\"en\">\n    <meta charset=\"UTF-8\">\n    <title>WiFi Station Config</title>\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"wifi_portal.css\">\n    <!-- <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" /> -->\n</head>\n<div class=\"login-page\">\n    <div class=\"form\">\n        <p class=\"title\">Connect to WiFi AP</p>\n        <form class=\"login-form\" action=\"javascript:void(0);\">\n            <input id=\"ssid_input\" type=\"text\" maxlength=31 placeholder=\"SSID\" />\n            <input id=\"password_input\" type=\"password\" maxlength=63 placeholder=\"password\" />\n            <button onclick=\"submitData()\">Connect</button>\n        </form>\n        <p class=\"status\">Connect to WiFi AP</p>\n    </div>\n</div>\n\n<script>\n    async function submitData() {\n        const ssid = document.getElementById(\"ssid_input\").value;\n        const password = document.getElementById(\"password_input\").value;\n\n        const body = { ssid, password };\n\n        const response = await fetch(window.location.href + 'connect', {\n            method: \"POST\",\n            headers: {\n                \"Content-Type\": \"application/json\"\n            },\n            body: JSON.stringify(body)\n        });\n\n        const serverResponse = await response;\n\n        const status = document.getElementsByClassName('status')[0];\n        if (serverResponse.ok) {\n            const form = document.getElementsByClassName('login-form')[0];\n            const title = document.getElementsByClassName('title')[0];\n\n            form.style.display = \"none\"\n            title.style.display = \"none\"\n            status.style.padding = \"16px 0px 0px 0px\"\n\n            status.style.color = \"#11c1f3\";\n        } else {\n            status.style.color = \"#f31111\";\n        }\n        status.textContent = await serverResponse.text();\n        status.style.display = \"block\";\n    }\n</script>";

const char* wifi_portal_css_src = ".login-page {\n    font-family: 'Segoe UI Symbol', Geneva, Tahoma, Verdana, Roboto, Arial, sans-serif;\n    font-size: 14px;\n    padding: 2%;\n    width: 96%;\n    max-width: 400px;\n    margin: 0 auto;\n    position: fixed;\n    top: 50%;\n    left: 50%;\n    -webkit-transform: translate(-50%, -50%);\n    transform: translate(-50%, -50%);\n}\n\n.header ul {\n    padding: 0;\n}\n\n.icon {\n    position: absolute;\n    right: 80px;\n    font-size: 24px;\n    line-height: 1em;\n    color: #aaa;\n}\n\n.badge {\n    position: absolute;\n    right: 32px;\n    color: #444;\n    background-color: #bbdefb;\n    padding: 0 8px;\n    border-radius: 12px;\n    line-height: 1.8em;\n}\n\n.selected {\n    color: #fafafa !important;\n    background-color: #11c1f3 !important;\n}\n\n.header li {\n    text-align: left;\n    padding: 8px 16px;\n    list-style-type: none;\n    margin-bottom: 4px;\n    line-height: 2em;\n    border-radius: 8px;\n    color: #444;\n    background-color: #fafafa;\n    border: solid 2px #bbdefb;\n}\n\n.title {\n    text-align: center;\n    color: #11c1f3;\n    font-size: 20px;\n    padding: 0px 0px 0px 0px;\n}\n\n.status {\n    text-align: center;\n    font-size: 20px;\n    padding: 0px 0px 0px 0px;\n    display: none;\n}\n\n\n.form {\n    position: relative;\n    background: #fafafa;\n    font-weight: bold;\n    padding: 4px 16px 16px 16px;\n    box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);\n    border-radius: 10px;\n}\n\n.form input {\n    width: 100%;\n    border: none;\n    background: #f2f2f2;\n    border-bottom: 3px solid #bbdefb;\n    outline-color: #bbdefb;\n    padding: 16px;\n    box-sizing: border-box;\n    margin-bottom: 8px;\n}\n\n.form button {\n    color: #fafafa;\n    background: #11c1f3;\n    border: solid 2px #bbdefb;\n    border-radius: 8px;\n    text-transform: uppercase;\n    outline: 0;\n    width: 100%;\n    padding: 16px;\n    margin-top: 8px;\n}\n\n.form button:hover,\n.form button:focus {\n    background: #387ef5;\n}\n\ninput {\n    border-radius: 10px;\n}\n\nbody {\n    background: #387ef5;\n    background: -webkit-linear-gradient(right, #387ef5, #b98fd9);\n    background: -moz-linear-gradient(right, #387ef5, #b98fd9);\n    background: -o-linear-gradient(right, #387ef5, #b98fd9);\n    background: linear-gradient(to left, #387ef5, #b98fd9);\n    -webkit-font-smoothing: antialiased;\n    -moz-osx-font-smoothing: grayscale;\n}";

#endif

